@startuml state_machine_diagram
skinparam monochrome true 
skinparam shadowing false
left to right direction

state 初期画面 {
  イベント一覧 -> イベント一覧: 削除する
  カレンダー一覧 -> カレンダー一覧: 削除する 
}

イベント作成 --> イベント一覧: キャンセル
イベント一覧 --> イベント作成: 作成する
イベント一覧 --> イベント詳細: 詳細を見る
イベント詳細 --> イベント一覧: 閉じる
イベント詳細 --> イベント編集: 編集する 
イベント編集 --> イベント詳細: キャンセル

カレンダー一覧 --> カレンダー作成: 作成する
カレンダー作成 --> カレンダー一覧: キャンセル
カレンダー一覧 --> カレンダー編集: 編集する
カレンダー編集 --> カレンダー一覧: キャンセル
@enduml 
